apiVersion: v1
kind: Pod
metadata:
  name: nfs--pod
spec:
  restartPolicy: Never
  containers:
    - image: busybox
      name: busybox
      #command: ['sh', '-c', 'echo Success!!! > /output/success.txt']
      command: ['sh', '-c', 'while true; do echo Siva!!! >> /output/output.txt; sleep 5; done']
      volumeMounts:
        - name: my-volume
          mountPath: /output
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: nfs-claim